development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: hindustani
  password: hindustani

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: hindustani
  password: hindustani


production:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: hindustani
  password: hindustani
